burl: https://federicadomani.github.io
real_www: federicadomani.github.io
bdate: 2025-11-25

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: favicon_large.png
author: Open Source Developer Federica Domani
title: AutoClicker2 Record Play | Modern OP Auto Clicker fork
description_rich: Modern 2025 OP Auto Clicker fork to record, edit, import, debug, and playback the whole sequences of mouse clicks with the 5 mouse buttons support
description: Modern 2025 OP Auto Clicker fork to record, edit, import, debug, and playback the whole sequences of mouse clicks with the 5 mouse buttons support
app_name: AutoClicker2 Record Play
app_name_ex: AutoClicker2Ex Record Play
app_version: 5.9.9.0
